name:                bunyan
version:             0.1.0.0
github:              "grmble/hs-bunyan"
license:             MIT
author:              "Juergen Gmeiner"
maintainer:          "spamless.juergen@gmail.com"
copyright:           "(c) 2018,2019 Juergen Gmeiner"

extra-source-files:
- README.md


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Bunyan-style logging for Haskell

# base 4.10 is stack lts 10 aka GHC 8.2.2
dependencies:
- base >= 4.10 && < 5
- bytestring
- aeson
- bunyan-pid
- clock
- formatting
- hostname
- network
- picolens
- scientific
- text
- time
- unliftio
- unordered-containers

library:
  source-dirs: src

tests:
  bunyan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bunyan
    - hspec
    - QuickCheck

benchmarks:
  bunyan-bench:
    source-dirs: bench
    main: Main.hs
    ghc-options: -O2
    dependencies:
    - criterion
    - bunyan

#
# ghc options and default extensions ... see
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
#

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators



